apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.8.3
    chart: ingress-nginx
    helm:
      valuesObject:
        controller:
          hostPort:
            enabled: true
          terminationGracePeriodSeconds: 0
          service:
            type: "NodePort"
          watchIngressWithoutClass: true
          nodeSelector:
            ingress-ready: "true"
          tolerations:
          - effect: "NoSchedule"
            key: "node-role.kubernetes.io/master"
            operator: "Equal"
          - effect: "NoSchedule"
            key: "node-role.kubernetes.io/control-plane"
            operator: "Equal"
          publishService:
            enabled: false
          extraArgs:
            publish-status-address: "localhost"
  project: infra
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
