apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt-issuers
  namespace: argocd
  finalizers:
    # The default behaviour is foreground cascading deletion
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/project-seseal/k8s.git
    targetRevision: main
    path: infra

    kustomize: {}
  project: infra
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
